name: Run selenium pytest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from github
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Install Chrome library
        uses: browser-actions/setup-chrome@v1

      - name: Create a test report Folder
        run: mkdir -p reports

      - name: Run Tests
        run: pytest -m smoke --html=reports/report.html --self-contained-html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pytest report
          path: reports/report.html